### PR TITLE
chore: fixes github actions for ruleserver.

### PR DESCRIPTION
**Pull request by jcchavezs**
Fixes ruleserver github action.

### CODE REVIEW

**Comment by jcchavezs** [comment]
@bryanwux @leyao-daily tests for ruleserver are failing (see https://github.com/intel/modsecurity-wasm-filter/runs/6171881830?check_suite_focus=true#step:7:16). Do you have any clue on why?

**Comment by leyao-daily** [comment]
It seems that some pre-requirments is not met. The build need kubebuilder and which require kustomize and controller-gen.

**Comment by jcchavezs** [comment]
This is green.

**Comment by leyao-daily** [comment]
LGTM. @jcchavezs  Thanks, and please squash your commits into one.

**Comment by jcchavezs** [comment]
Can't we squash it on merge?

**Comment by leyao-daily** [comment]
> Can't we squash it on merge?

It makes sense. And please sign off your commits.

**Comment by jcchavezs** [comment]
Will do that.

tir. 26. apr. 2022, 16:02 skrev Le Yao ***@***.***>:

**Comment by jcchavezs** [comment]
> About Squash and rebase, if I do this action, whether it will change the commits author or not?

Nope it won't, for example see https://github.com/openzipkin/zipkin/commit/b9e38f22788d9308d69a49fbcf4ac4cf2ef35c65 where I squashed and merged the PR.

I just signed off my commits.

**Comment by leyao-daily** [comment]
Thanks a lot for your contribution.

**Comment by jcchavezs** [comment]
Can't we squash on merge instead?

tir. 26. apr. 2022, 13:28 skrev Le Yao ***@***.***>:

**Pull request merged**
