### PR TITLE
chore: upgrades emsdk activated version to 2.0.22

### PR DESCRIPTION
**Pull request by jcchavezs**

### CODE REVIEW

**Comment by leyao-daily** [comment]
Can we update the version to 3.1.7, I find that the proxy-wasm sdk have support emsdk [3.1.7](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk#emscripten)

**Comment by jcchavezs** [comment]
@leyao-daily trying here https://github.com/intel/modsecurity-wasm-filter/pull/21

**Comment by leyao-daily** [comment]
Is this PR used to verify the running status of the CI when using different emsdk version?

**Comment by jcchavezs** [comment]
Yes, my plan was to try different versions to see what version we can get to.

**Comment by M4tteoP** [comment]
Worth another try, but back in the days I did a quick and dirty test trying to update the `emsdk` version to `3.1.7`.
I had build problems and I think that they were related to the other build dependencies that we use.
 Specifically, we may have to keep consistent the LLVM version (otherwise the good old `_ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKc` error at runtime spawns again).
 As far as I understand:
 - Both emsdk v2.0.7 and [wasi-sdk-12](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-12), are based on LLVM 11. If my hunch is right, we should be able to update `emsdk` up to 2.0.22 and from 2.0.23 It will fail.
 - It would be possible to also update the `wasi-sdk`, but I bumped into `libpcre` build problems and I did not dig further. Still, update the whole build chain should be the way to go

**Comment by M4tteoP** [comment]
Reading [this comment](https://github.com/emscripten-core/emscripten/issues/10326#issuecomment-640884035), there may be a way to use an updated `emsdk` but still point to a previous LLVM version.

**Comment by jcchavezs** [comment]
Can we merge this @leyao-daily ?

**Comment by M4tteoP** [comment]
Issue https://github.com/intel/modsecurity-wasm-filter/issues/23 created. I wrote a recap and added some links to release notes. Please add details if I missed something!

**Comment by leyao-daily** [comment]
LGTM. Please sign off your commit.

**Comment by jcchavezs** [comment]
Superseeded by https://github.com/intel/modsecurity-wasm-filter/pull/24

**Pull request closed without merging**
